export const DEFAULT_SETTINGS = {
  design: "ccc",
  shape: "halfRounded",
  shadow: null,
  titleText: "You might also like…",
  noThxText: "Nah, i’m good",
  ctaText: "Continue",
  isCtaPriceActive: true,
  addText: "Add",
  addedText: "Added",
  backText: "Back to offers",
  primaryColor: {
    hex: "#7D6541",
    hsl: {
      brightness: 0.48,
      hue: 157.55,
      saturation: 0.6,
    },
  },
  secondaryColor: {
    hex: "#7D6541",
    hsl: {
      brightness: 0.54,
      hue: 343,
      saturation: 1,
    },
  },
  noThxColor: {
    hex: "#000",
    hsl: {
      brightness: 0,
      hue: 0,
      saturation: 0,
    },
  },
  timerColor: {
    hex: "#eee8e5",
    hsl: { brightness: 0.46, hue: 220, saturation: 0.09 },
  },
  shippingBarColor: {
    hex: "#f2e3d7",
    hsl: { brightness: 0.46, hue: 220, saturation: 0.09 },
  },
  actionColor: {
    hex: "#7D6541",
    hsl: {
      brightness: 0.48,
      hue: 157.55,
      saturation: 0.6,
    },
  },
  actionColorInverse: false,
  isIconsBarActive: true,
  iconsBarLeft: "✈️ FREE SHIPPING WORLDWIDE",
  iconsBarRight: "✔️ FREE RETURNS WORLDWIDE",
  isFreeShippingBarActive: true,
  freeShippingBarAmount: "10",
  freeShippingBarTextProgress: "{amount} remaining to get free shipping",
  freeShippingBarTextSucess: "🎉  You got it!",
  isTimerActive: true,
  timerDuration: "7",
  timerText: "Special offer ends in: ",
  displayProduct: false,
  topProductAddedToCartText: "In your cart",
  freeProductText: "FREE",
  discountText: "Discount {{discount}}% will be applied at checkout.",
  customDiscountText: "Discount code will be applied at checkout.",
  discountCode: "",
  readMoreText: "Read more",
  oneTimePerSession: false,
  selectedPerDefault: false,
  customCSS: "",
  limit: {},
  hideIfExistsInCart: false,
  hideIfProductsInCart: false,
  // hideIfCollectionsInCart: false,
  removeWithProduct: false,
  showTo: "",
  redirect: "default"
};
